package com.ihm.customer.entites;

// Generated 24 Jan, 2015 3:46:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * CstAddress generated by hbm2java
 */
@Entity
@Table(name = "cst_address")
public class CstAddress implements java.io.Serializable {

	private long id;
	private Integer version;
	private CstUsers cstUsers;
	private String address1;
	private String address2;
	private String addressType;
	private String city;
	private String country;
	private String createdBy;
	private Date createdOn;
	private String disableFlg;
	private String locality;
	private String state;
	private String timeZone;
	private String updatedBy;
	private Date updatedOn;
	private String zip;

	public CstAddress() {
	}

	public CstAddress(long id) {
		this.id = id;
	}

	public CstAddress(long id, CstUsers cstUsers, String address1,
			String address2, String addressType, String city, String country,
			String createdBy, Date createdOn, String disableFlg,
			String locality, String state, String timeZone, String updatedBy,
			Date updatedOn, String zip) {
		this.id = id;
		this.cstUsers = cstUsers;
		this.address1 = address1;
		this.address2 = address2;
		this.addressType = addressType;
		this.city = city;
		this.country = country;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.disableFlg = disableFlg;
		this.locality = locality;
		this.state = state;
		this.timeZone = timeZone;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
		this.zip = zip;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_name")
	public CstUsers getCstUsers() {
		return this.cstUsers;
	}

	public void setCstUsers(CstUsers cstUsers) {
		this.cstUsers = cstUsers;
	}

	@Column(name = "address1")
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2")
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "address_type")
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "disable_flg")
	public String getDisableFlg() {
		return this.disableFlg;
	}

	public void setDisableFlg(String disableFlg) {
		this.disableFlg = disableFlg;
	}

	@Column(name = "locality")
	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "time_zone")
	public String getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Column(name = "zip")
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

}
