package com.ihm.customer.entites;

// Generated 24 Jan, 2015 3:46:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CstRoles generated by hbm2java
 */
@Entity
@Table(name = "cst_roles", uniqueConstraints = @UniqueConstraint(columnNames = "ROLE"))
public class CstRoles implements java.io.Serializable {

	private Integer id;
	private String role;
	private String username;
	private Set<CstUsers> cstUserses = new HashSet<CstUsers>(0);

	public CstRoles() {
	}

	public CstRoles(String role) {
		this.role = role;
	}

	public CstRoles(String role, Set<CstUsers> cstUserses) {
		this.role = role;
		this.cstUserses = cstUserses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	@Column(name = "username", unique = true, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
	@Column(name = "ROLE", unique = true, nullable = false, length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cstRoles")
	public Set<CstUsers> getCstUserses() {
		return this.cstUserses;
	}

	public void setCstUserses(Set<CstUsers> cstUserses) {
		this.cstUserses = cstUserses;
	}

}
