package com.ihm.customer.entites;

// Generated 24 Jan, 2015 12:32:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * CstUserCredential generated by hbm2java
 */
@Entity
@Table(name = "cst_user_credential")
public class CstUserCredential implements java.io.Serializable {

	private long id;
	private Integer version;
	private String createdBy;
	private Date createdOn;
	private String disableFlg;
	private String passKey;
	private Date passwordExpiryDate;
	private String updatedBy;
	private Date updatedOn;
	private Date userActivationDate;
	private String userActiveFlg;
	private String userCategory;
	private Date userExpiryDate;
	private String userId;
	private String userLockedFlg;
	private Integer userLoginAttempt;

	public CstUserCredential() {
	}

	public CstUserCredential(long id) {
		this.id = id;
	}

	public CstUserCredential(long id, String createdBy, Date createdOn,
			String disableFlg, String passKey, Date passwordExpiryDate,
			String updatedBy, Date updatedOn, Date userActivationDate,
			String userActiveFlg, String userCategory, Date userExpiryDate,
			String userId, String userLockedFlg, Integer userLoginAttempt) {
		this.id = id;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.disableFlg = disableFlg;
		this.passKey = passKey;
		this.passwordExpiryDate = passwordExpiryDate;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
		this.userActivationDate = userActivationDate;
		this.userActiveFlg = userActiveFlg;
		this.userCategory = userCategory;
		this.userExpiryDate = userExpiryDate;
		this.userId = userId;
		this.userLockedFlg = userLockedFlg;
		this.userLoginAttempt = userLoginAttempt;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "disable_flg")
	public String getDisableFlg() {
		return this.disableFlg;
	}

	public void setDisableFlg(String disableFlg) {
		this.disableFlg = disableFlg;
	}

	@Column(name = "pass_key")
	public String getPassKey() {
		return this.passKey;
	}

	public void setPassKey(String passKey) {
		this.passKey = passKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "password_expiry_date", length = 19)
	public Date getPasswordExpiryDate() {
		return this.passwordExpiryDate;
	}

	public void setPasswordExpiryDate(Date passwordExpiryDate) {
		this.passwordExpiryDate = passwordExpiryDate;
	}

	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_activation_date", length = 19)
	public Date getUserActivationDate() {
		return this.userActivationDate;
	}

	public void setUserActivationDate(Date userActivationDate) {
		this.userActivationDate = userActivationDate;
	}

	@Column(name = "user_active_flg")
	public String getUserActiveFlg() {
		return this.userActiveFlg;
	}

	public void setUserActiveFlg(String userActiveFlg) {
		this.userActiveFlg = userActiveFlg;
	}

	@Column(name = "user_category")
	public String getUserCategory() {
		return this.userCategory;
	}

	public void setUserCategory(String userCategory) {
		this.userCategory = userCategory;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_expiry_date", length = 19)
	public Date getUserExpiryDate() {
		return this.userExpiryDate;
	}

	public void setUserExpiryDate(Date userExpiryDate) {
		this.userExpiryDate = userExpiryDate;
	}

	@Column(name = "user_id")
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "user_locked_flg")
	public String getUserLockedFlg() {
		return this.userLockedFlg;
	}

	public void setUserLockedFlg(String userLockedFlg) {
		this.userLockedFlg = userLockedFlg;
	}

	@Column(name = "user_login_attempt")
	public Integer getUserLoginAttempt() {
		return this.userLoginAttempt;
	}

	public void setUserLoginAttempt(Integer userLoginAttempt) {
		this.userLoginAttempt = userLoginAttempt;
	}

}
