package com.ihm.customer.entites;

// Generated 24 Jan, 2015 3:46:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CstUsers generated by hbm2java
 */
@Entity
@Table(name = "cst_users", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class CstUsers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9000849208937668027L;
	
	
	private Integer id;
	private CstRoles cstRoles;
	private String username;
	private String firstName;
	private String lastName;
	private String email;
	private String password;
	private String primaryNumber;
	private String dob;
	private Boolean appointmentReminder;
	private Boolean onlineSurveyUsername;
	private Boolean specialOfferUsername;
	private Byte enabled;
	private Set<CstAddress> cstAddresses = new HashSet<CstAddress>(0);

	public CstUsers() {
	}

	public CstUsers(CstRoles cstRoles, String username, String firstName,
			String lastName, String email, String password,
			String primaryNumber, String dob, Boolean appointmentReminder,
			Boolean onlineSurveyUsername, Boolean specialOfferUsername,
			Byte enabled, Set<CstAddress> cstAddresses) {
		this.cstRoles = cstRoles;
		this.username = username;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.primaryNumber = primaryNumber;
		this.dob = dob;
		this.appointmentReminder = appointmentReminder;
		this.onlineSurveyUsername = onlineSurveyUsername;
		this.specialOfferUsername = specialOfferUsername;
		this.enabled = enabled;
		this.cstAddresses = cstAddresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public CstRoles getCstRoles() {
		return this.cstRoles;
	}

	public void setCstRoles(CstRoles cstRoles) {
		this.cstRoles = cstRoles;
	}

	@Column(name = "username", unique = true, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "first_name", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", length = 60)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "primary_number", length = 60)
	public String getPrimaryNumber() {
		return this.primaryNumber;
	}

	public void setPrimaryNumber(String primaryNumber) {
		this.primaryNumber = primaryNumber;
	}

	@Column(name = "dob", length = 45)
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "appointment_reminder")
	public Boolean getAppointmentReminder() {
		return this.appointmentReminder;
	}

	public void setAppointmentReminder(Boolean appointmentReminder) {
		this.appointmentReminder = appointmentReminder;
	}

	@Column(name = "online_survey_username")
	public Boolean getOnlineSurveyUsername() {
		return this.onlineSurveyUsername;
	}

	public void setOnlineSurveyUsername(Boolean onlineSurveyUsername) {
		this.onlineSurveyUsername = onlineSurveyUsername;
	}

	@Column(name = "special_offer_username")
	public Boolean getSpecialOfferUsername() {
		return this.specialOfferUsername;
	}

	public void setSpecialOfferUsername(Boolean specialOfferUsername) {
		this.specialOfferUsername = specialOfferUsername;
	}

	@Column(name = "enabled")
	public Byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Byte enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cstUsers")
	public Set<CstAddress> getCstAddresses() {
		return this.cstAddresses;
	}

	public void setCstAddresses(Set<CstAddress> cstAddresses) {
		this.cstAddresses = cstAddresses;
	}

}
