package com.ihm.customer.entites;

// Generated 3 Jan, 2015 12:02:40 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IdSequence generated by hbm2java
 */
@Entity
@Table(name = "id_sequence")
public class IdSequence implements java.io.Serializable {

	private IdSequenceId id;

	public IdSequence() {
	}

	public IdSequence(IdSequenceId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "sequenceName", column = @Column(name = "sequence_name")),
			@AttributeOverride(name = "nextId", column = @Column(name = "next_id")) })
	public IdSequenceId getId() {
		return this.id;
	}

	public void setId(IdSequenceId id) {
		this.id = id;
	}

}
