package com.ihm.customer.entites;

// Generated 3 Jan, 2015 12:02:40 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IdSequenceId generated by hbm2java
 */
@Embeddable
public class IdSequenceId implements java.io.Serializable {

	private String sequenceName;
	private Integer nextId;

	public IdSequenceId() {
	}

	public IdSequenceId(String sequenceName, Integer nextId) {
		this.sequenceName = sequenceName;
		this.nextId = nextId;
	}

	@Column(name = "sequence_name")
	public String getSequenceName() {
		return this.sequenceName;
	}

	public void setSequenceName(String sequenceName) {
		this.sequenceName = sequenceName;
	}

	@Column(name = "next_id")
	public Integer getNextId() {
		return this.nextId;
	}

	public void setNextId(Integer nextId) {
		this.nextId = nextId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IdSequenceId))
			return false;
		IdSequenceId castOther = (IdSequenceId) other;

		return ((this.getSequenceName() == castOther.getSequenceName()) || (this
				.getSequenceName() != null
				&& castOther.getSequenceName() != null && this
				.getSequenceName().equals(castOther.getSequenceName())))
				&& ((this.getNextId() == castOther.getNextId()) || (this
						.getNextId() != null && castOther.getNextId() != null && this
						.getNextId().equals(castOther.getNextId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getSequenceName() == null ? 0 : this.getSequenceName()
						.hashCode());
		result = 37 * result
				+ (getNextId() == null ? 0 : this.getNextId().hashCode());
		return result;
	}

}
