package com.ihm.customer.entites;

// Generated 30 Jan, 2015 2:34:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * IhmCountry generated by hbm2java
 */
@Entity
@Table(name = "ihm_country")
public class IhmCountry implements java.io.Serializable {

	private long id;
	private Integer version;
	private String code;
	private String createdBy;
	private Date createdOn;
	private String description;
	private String disableFlg;
	private String updatedBy;
	private Date updatedOn;
	private Set<IhmStateInfo> ihmStateInfos = new HashSet<IhmStateInfo>(0);

	public IhmCountry() {
	}

	public IhmCountry(long id) {
		this.id = id;
	}

	public IhmCountry(long id, String code, String createdBy, Date createdOn,
			String description, String disableFlg, String updatedBy,
			Date updatedOn, Set<IhmStateInfo> ihmStateInfos) {
		this.id = id;
		this.code = code;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.description = description;
		this.disableFlg = disableFlg;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
		this.ihmStateInfos = ihmStateInfos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "disable_flg")
	public String getDisableFlg() {
		return this.disableFlg;
	}

	public void setDisableFlg(String disableFlg) {
		this.disableFlg = disableFlg;
	}

	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ihmCountry")
	public Set<IhmStateInfo> getIhmStateInfos() {
		return this.ihmStateInfos;
	}

	public void setIhmStateInfos(Set<IhmStateInfo> ihmStateInfos) {
		this.ihmStateInfos = ihmStateInfos;
	}

}
