package com.ihm.customer.entites;

// Generated 30 Jan, 2015 2:34:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * IhmCategories generated by hbm2java
 */
@Entity
@Table(name = "ihm_categories")
public class IhmCategories implements java.io.Serializable {

	private long id;
	private Integer version;
	private String createdBy;
	private Date createdOn;
	private String name;
	private String subCategoryName;
	private String updatedBy;
	private Date updatedOn;
	private Set<SlrDeal> slrDeals = new HashSet<SlrDeal>(0);
	private Set<SlrProduct> slrProducts = new HashSet<SlrProduct>(0);

	public IhmCategories() {
	}

	public IhmCategories(long id) {
		this.id = id;
	}

	public IhmCategories(long id, String createdBy, Date createdOn,
			String name, String subCategoryName, String updatedBy,
			Date updatedOn, Set<SlrDeal> slrDeals, Set<SlrProduct> slrProducts) {
		this.id = id;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.name = name;
		this.subCategoryName = subCategoryName;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
		this.slrDeals = slrDeals;
		this.slrProducts = slrProducts;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sub_category_name")
	public String getSubCategoryName() {
		return this.subCategoryName;
	}

	public void setSubCategoryName(String subCategoryName) {
		this.subCategoryName = subCategoryName;
	}

	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "slr_deal_category_xref", joinColumns = { @JoinColumn(name = "category_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "deal_id", nullable = false, updatable = false) })
	public Set<SlrDeal> getSlrDeals() {
		return this.slrDeals;
	}

	public void setSlrDeals(Set<SlrDeal> slrDeals) {
		this.slrDeals = slrDeals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ihmCategories")
	public Set<SlrProduct> getSlrProducts() {
		return this.slrProducts;
	}

	public void setSlrProducts(Set<SlrProduct> slrProducts) {
		this.slrProducts = slrProducts;
	}

}
