package com.ihm.customer.entites;

// Generated 30 Jan, 2015 2:34:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * IhmLoginHistory generated by hbm2java
 */
@Entity
@Table(name = "ihm_login_history")
public class IhmLoginHistory implements java.io.Serializable {

	private long id;
	private Integer version;
	private UserProfile userProfile;
	private String ipAddress;
	private Date logoutOn;
	private String sessionId;
	private Date startedOn;
	private String userAgent;

	public IhmLoginHistory() {
	}

	public IhmLoginHistory(long id) {
		this.id = id;
	}

	public IhmLoginHistory(long id, UserProfile userProfile, String ipAddress,
			Date logoutOn, String sessionId, Date startedOn, String userAgent) {
		this.id = id;
		this.userProfile = userProfile;
		this.ipAddress = ipAddress;
		this.logoutOn = logoutOn;
		this.sessionId = sessionId;
		this.startedOn = startedOn;
		this.userAgent = userAgent;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_profile")
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "ip_address")
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logout_on", length = 19)
	public Date getLogoutOn() {
		return this.logoutOn;
	}

	public void setLogoutOn(Date logoutOn) {
		this.logoutOn = logoutOn;
	}

	@Column(name = "session_id")
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "started_on", length = 19)
	public Date getStartedOn() {
		return this.startedOn;
	}

	public void setStartedOn(Date startedOn) {
		this.startedOn = startedOn;
	}

	@Column(name = "user_agent")
	public String getUserAgent() {
		return this.userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}

}
