package com.ihm.customer.entites;

// Generated 24 Jan, 2015 3:46:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SlrAppointmentSlots generated by hbm2java
 */
@Entity
@Table(name = "slr_appointment_slots")
public class SlrAppointmentSlots implements java.io.Serializable {

	private Long id;
	private Integer version;
	private boolean active;
	private String createdBy;
	private Date createdOn;
	private Date slotTime;
	private String updatedBy;
	private Date updatedOn;
	
	private SlrSeller slrSeller;
	private SlrAppointment slrAppointment;
	private Set<SlrAppointmentBookings> slrAppointmentBookingses = new HashSet<SlrAppointmentBookings>(0);

	public SlrAppointmentSlots() {
	}

	public SlrAppointmentSlots(boolean active) {
		this.active = active;
	}

	public SlrAppointmentSlots(SlrAppointment slrAppointment,
			SlrSeller slrSeller, boolean active, String createdBy,
			Date createdOn, Date slotTime, String updatedBy, Date updatedOn,
			Set<SlrAppointmentBookings> slrAppointmentBookingses) {
		this.slrAppointment = slrAppointment;
		this.slrSeller = slrSeller;
		this.active = active;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.slotTime = slotTime;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
		this.slrAppointmentBookingses = slrAppointmentBookingses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seller_appt_id")
	public SlrAppointment getSlrAppointment() {
		return this.slrAppointment;
	}

	public void setSlrAppointment(SlrAppointment slrAppointment) {
		this.slrAppointment = slrAppointment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seller_id")
	public SlrSeller getSlrSeller() {
		return this.slrSeller;
	}

	public void setSlrSeller(SlrSeller slrSeller) {
		this.slrSeller = slrSeller;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "slot_time", length = 8)
	public Date getSlotTime() {
		return this.slotTime;
	}

	public void setSlotTime(Date slotTime) {
		this.slotTime = slotTime;
	}

	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slrAppointmentSlots")
	public Set<SlrAppointmentBookings> getSlrAppointmentBookingses() {
		return this.slrAppointmentBookingses;
	}

	public void setSlrAppointmentBookingses(
			Set<SlrAppointmentBookings> slrAppointmentBookingses) {
		this.slrAppointmentBookingses = slrAppointmentBookingses;
	}

}
