package com.ihm.customer.entites;

// Generated 24 Jan, 2015 3:46:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SlrDeal generated by hbm2java
 */
@Entity
@Table(name = "slr_deal")
public class SlrDeal implements java.io.Serializable {

	private long id;
	private Integer version;
	private SlrSeller slrSeller;
	private BigDecimal applyEndAmount;
	private BigDecimal applyGreaterAmount;
	private BigDecimal applyLesserAmount;
	private BigDecimal applyStartAmount;
	private String createdBy;
	private Date createdOn;
	private String description;
	private BigDecimal discountAmount;
	private String discountAmtCurCode;
	private String discountCode;
	private BigDecimal discountPercentage;
	private Date endDate;
	private String name;
	private String priceBase;
	private String productBase;
	private Date startDate;
	private String status;
	private String termsAndConditions;
	private String updatedBy;
	private Date updatedOn;
	private Set<SlrProduct> slrProducts = new HashSet<SlrProduct>(0);
	private Set<IhmCategories> ihmCategorieses = new HashSet<IhmCategories>(0);

	public SlrDeal() {
	}

	public SlrDeal(long id) {
		this.id = id;
	}

	public SlrDeal(long id, SlrSeller slrSeller, BigDecimal applyEndAmount,
			BigDecimal applyGreaterAmount, BigDecimal applyLesserAmount,
			BigDecimal applyStartAmount, String createdBy, Date createdOn,
			String description, BigDecimal discountAmount,
			String discountAmtCurCode, String discountCode,
			BigDecimal discountPercentage, Date endDate, String name,
			String priceBase, String productBase, Date startDate,
			String status, String termsAndConditions, String updatedBy,
			Date updatedOn, Set<SlrProduct> slrProducts,
			Set<IhmCategories> ihmCategorieses) {
		this.id = id;
		this.slrSeller = slrSeller;
		this.applyEndAmount = applyEndAmount;
		this.applyGreaterAmount = applyGreaterAmount;
		this.applyLesserAmount = applyLesserAmount;
		this.applyStartAmount = applyStartAmount;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.description = description;
		this.discountAmount = discountAmount;
		this.discountAmtCurCode = discountAmtCurCode;
		this.discountCode = discountCode;
		this.discountPercentage = discountPercentage;
		this.endDate = endDate;
		this.name = name;
		this.priceBase = priceBase;
		this.productBase = productBase;
		this.startDate = startDate;
		this.status = status;
		this.termsAndConditions = termsAndConditions;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
		this.slrProducts = slrProducts;
		this.ihmCategorieses = ihmCategorieses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seller_id")
	public SlrSeller getSlrSeller() {
		return this.slrSeller;
	}

	public void setSlrSeller(SlrSeller slrSeller) {
		this.slrSeller = slrSeller;
	}

	@Column(name = "apply_end_amount")
	public BigDecimal getApplyEndAmount() {
		return this.applyEndAmount;
	}

	public void setApplyEndAmount(BigDecimal applyEndAmount) {
		this.applyEndAmount = applyEndAmount;
	}

	@Column(name = "apply_greater_amount")
	public BigDecimal getApplyGreaterAmount() {
		return this.applyGreaterAmount;
	}

	public void setApplyGreaterAmount(BigDecimal applyGreaterAmount) {
		this.applyGreaterAmount = applyGreaterAmount;
	}

	@Column(name = "apply_lesser_amount")
	public BigDecimal getApplyLesserAmount() {
		return this.applyLesserAmount;
	}

	public void setApplyLesserAmount(BigDecimal applyLesserAmount) {
		this.applyLesserAmount = applyLesserAmount;
	}

	@Column(name = "apply_start_amount")
	public BigDecimal getApplyStartAmount() {
		return this.applyStartAmount;
	}

	public void setApplyStartAmount(BigDecimal applyStartAmount) {
		this.applyStartAmount = applyStartAmount;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "discount_amount")
	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "discount_amt_cur_code")
	public String getDiscountAmtCurCode() {
		return this.discountAmtCurCode;
	}

	public void setDiscountAmtCurCode(String discountAmtCurCode) {
		this.discountAmtCurCode = discountAmtCurCode;
	}

	@Column(name = "discount_code")
	public String getDiscountCode() {
		return this.discountCode;
	}

	public void setDiscountCode(String discountCode) {
		this.discountCode = discountCode;
	}

	@Column(name = "discount_percentage")
	public BigDecimal getDiscountPercentage() {
		return this.discountPercentage;
	}

	public void setDiscountPercentage(BigDecimal discountPercentage) {
		this.discountPercentage = discountPercentage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price_base")
	public String getPriceBase() {
		return this.priceBase;
	}

	public void setPriceBase(String priceBase) {
		this.priceBase = priceBase;
	}

	@Column(name = "product_base")
	public String getProductBase() {
		return this.productBase;
	}

	public void setProductBase(String productBase) {
		this.productBase = productBase;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "terms_and_conditions")
	public String getTermsAndConditions() {
		return this.termsAndConditions;
	}

	public void setTermsAndConditions(String termsAndConditions) {
		this.termsAndConditions = termsAndConditions;
	}

	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "slr_deal_product_xref", joinColumns = { @JoinColumn(name = "deal_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "product_id", nullable = false, updatable = false) })
	public Set<SlrProduct> getSlrProducts() {
		return this.slrProducts;
	}

	public void setSlrProducts(Set<SlrProduct> slrProducts) {
		this.slrProducts = slrProducts;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "slr_deal_category_xref", joinColumns = { @JoinColumn(name = "deal_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "category_id", nullable = false, updatable = false) })
	public Set<IhmCategories> getIhmCategorieses() {
		return this.ihmCategorieses;
	}

	public void setIhmCategorieses(Set<IhmCategories> ihmCategorieses) {
		this.ihmCategorieses = ihmCategorieses;
	}

}
