package com.ihm.customer.entites;

// Generated 30 Jan, 2015 2:34:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SlrEducation generated by hbm2java
 */
@Entity
@Table(name = "slr_education")
public class SlrEducation implements java.io.Serializable {

	private long id;
	private Integer version;
	private SlrUserProfile slrUserProfile;
	private String createdBy;
	private Date createdOn;
	private String degree;
	private String description;
	private Integer endYear;
	private String school;
	private Integer startYear;
	private String updatedBy;
	private Date updatedOn;

	public SlrEducation() {
	}

	public SlrEducation(long id) {
		this.id = id;
	}

	public SlrEducation(long id, SlrUserProfile slrUserProfile,
			String createdBy, Date createdOn, String degree,
			String description, Integer endYear, String school,
			Integer startYear, String updatedBy, Date updatedOn) {
		this.id = id;
		this.slrUserProfile = slrUserProfile;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.degree = degree;
		this.description = description;
		this.endYear = endYear;
		this.school = school;
		this.startYear = startYear;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seller_user_profile")
	public SlrUserProfile getSlrUserProfile() {
		return this.slrUserProfile;
	}

	public void setSlrUserProfile(SlrUserProfile slrUserProfile) {
		this.slrUserProfile = slrUserProfile;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "degree")
	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "end_year")
	public Integer getEndYear() {
		return this.endYear;
	}

	public void setEndYear(Integer endYear) {
		this.endYear = endYear;
	}

	@Column(name = "school")
	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	@Column(name = "start_year")
	public Integer getStartYear() {
		return this.startYear;
	}

	public void setStartYear(Integer startYear) {
		this.startYear = startYear;
	}

	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

}
