package com.ihm.customer.entites;

// Generated 24 Jan, 2015 3:46:22 PM by Hibernate Tools 3.4.0.CR1

import org.hibernate.annotations.*;
import org.hibernate.annotations.CascadeType;

import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * SlrSeller generated by hbm2java
 */
@Entity
@Table(name = "slr_seller")
public class SlrSeller implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4993001518251432919L;
	
	
	private long id;
	private Integer version;
	private String code;
	private String createdBy;
	private Date createdOn;
	private String description;
	private String disableFlg;
	private String emailAddress;
	private String landLineNumber;
	private String landMark;
	private String mobileNumber;
	private String name;
	private String publicLink;
	private String registrationNumber;
	private String schedule;
	private String status;
	private String updatedBy;
	private Date updatedOn;
	private String webAddress;
	private String image1url;
	

	private String image2url;
	private String image3url;
	private String image4url;
	private String image5url;
	private String video_url;
	
	
	private SlrAddress slrAddress;
	
	private Set<SlrProduct> slrProducts = new HashSet<SlrProduct>(0);
	private Set<SlrDeal> prdDeals = new HashSet<SlrDeal>(0);
	private Set<SlrAmenities> slrAmenitieses = new HashSet<SlrAmenities>(0);
	private Set<SlrCertification> slrCertifications = new HashSet<SlrCertification>(0);
	private Set<SlrAward> slrAwards = new HashSet<SlrAward>(0);
	

	private Set<SlrAppointmentSlots> slrAppointmentSlotses = new HashSet<SlrAppointmentSlots>(0);
	private Set<SlrAppointmentBookings> slrAppointmentBookingses = new HashSet<SlrAppointmentBookings>(0);
	private Set<SlrSellerReview> slrSellerReviews = new HashSet<SlrSellerReview>(0);
	
	/*
	 * Not used in Customer Modules
	 */
	private Set<SlrUserProfile> slrUserProfiles = new HashSet<SlrUserProfile>(0);
	private Set<SlrUserProfile> slrUserProfiles_1 = new HashSet<SlrUserProfile>(0);
	private Set<SlrAppointment> slrAppointments = new HashSet<SlrAppointment>(0);
	

	public SlrSeller() {
	}

	public SlrSeller(long id) {
		this.id = id;
	}


	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "disable_flg")
	public String getDisableFlg() {
		return this.disableFlg;
	}

	public void setDisableFlg(String disableFlg) {
		this.disableFlg = disableFlg;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "registration_number")
	public String getRegistrationNumber() {
		return this.registrationNumber;
	}

	public void setRegistrationNumber(String registrationNumber) {
		this.registrationNumber = registrationNumber;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "updated_by")
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Column(name = "email_address")
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "land_line_number")
	public String getLandLineNumber() {
		return this.landLineNumber;
	}

	public void setLandLineNumber(String landLineNumber) {
		this.landLineNumber = landLineNumber;
	}

	@Column(name = "land_mark")
	public String getLandMark() {
		return this.landMark;
	}

	public void setLandMark(String landMark) {
		this.landMark = landMark;
	}

	@Column(name = "mobile_number")
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Column(name = "public_link")
	public String getPublicLink() {
		return this.publicLink;
	}

	public void setPublicLink(String publicLink) {
		this.publicLink = publicLink;
	}

	@Column(name = "schedule")
	public String getSchedule() {
		return this.schedule;
	}

	public void setSchedule(String schedule) {
		this.schedule = schedule;
	}

	@Column(name = "web_address")
	public String getWebAddress() {
		return this.webAddress;
	}

	public void setWebAddress(String webAddress) {
		this.webAddress = webAddress;
	}

	@Column(name = "image1url")
	public String getImage1url() {
		return image1url;
	}

	public void setImage1url(String image1url) {
		this.image1url = image1url;
	}
	@Column(name = "image2url")
	public String getImage2url() {
		return image2url;
	}

	public void setImage2url(String image2url) {
		this.image2url = image2url;
	}
	@Column(name = "image3url")
	public String getImage3url() {
		return image3url;
	}

	public void setImage3url(String image3url) {
		this.image3url = image3url;
	}
	@Column(name = "image4url")
	public String getImage4url() {
		return image4url;
	}

	public void setImage4url(String image4url) {
		this.image4url = image4url;
	}
	@Column(name = "image5url")
	public String getImage5url() {
		return image5url;
	}

	public void setImage5url(String image5url) {
		this.image5url = image5url;
	}
	@Column(name = "video_url")
	public String getVideo_url() {
		return video_url;
	}

	public void setVideo_url(String video_url) {
		this.video_url = video_url;
	}
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "slr_user_seller_xref", joinColumns = { @JoinColumn(name = "seller_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set<SlrUserProfile> getSlrUserProfiles() {
		return this.slrUserProfiles;
	}

	public void setSlrUserProfiles(Set<SlrUserProfile> slrUserProfiles) {
		this.slrUserProfiles = slrUserProfiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slrSeller")
	public Set<SlrUserProfile> getSlrUserProfiles_1() {
		return this.slrUserProfiles_1;
	}

	public void setSlrUserProfiles_1(Set<SlrUserProfile> slrUserProfiles_1) {
		this.slrUserProfiles_1 = slrUserProfiles_1;
	}
	
	
	
	/**
	 * Custom Hibernate Tunning
	 * 
	 */



	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slrSeller")
	@Cascade(CascadeType.ALL)
	@Fetch(FetchMode.SELECT)
    @BatchSize(size = 50)
	public Set<SlrAward> getSlrAwards() {
		return this.slrAwards;
	}

	public void setSlrAwards(Set<SlrAward> slrAwards) {
		this.slrAwards = slrAwards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slrSeller")
	@Cascade(CascadeType.ALL)
	@Fetch(FetchMode.SELECT)
    @BatchSize(size = 50)
	public Set<SlrCertification> getSlrCertifications() {
		return this.slrCertifications;
	}

	public void setSlrCertifications(Set<SlrCertification> slrCertifications) {
		this.slrCertifications = slrCertifications;
	}

	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slrSeller")
	@Cascade(CascadeType.ALL)
	@Fetch(FetchMode.SELECT)
    @BatchSize(size = 50)
	public Set<SlrAppointmentSlots> getSlrAppointmentSlotses() {
		return this.slrAppointmentSlotses;
	}

	public void setSlrAppointmentSlotses(
			Set<SlrAppointmentSlots> slrAppointmentSlotses) {
		this.slrAppointmentSlotses = slrAppointmentSlotses;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slrSeller")
	@Cascade(CascadeType.ALL)
	@Fetch(FetchMode.SELECT)
    @BatchSize(size = 50)
	public Set<SlrSellerReview> getSlrSellerReviews() {
		return this.slrSellerReviews;
	}

	public void setSlrSellerReviews(Set<SlrSellerReview> slrSellerReviews) {
		this.slrSellerReviews = slrSellerReviews;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slrSeller")
	public Set<SlrAppointment> getSlrAppointments() {
		return this.slrAppointments;
	}

	public void setSlrAppointments(Set<SlrAppointment> slrAppointments) {
		this.slrAppointments = slrAppointments;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slrSeller")
	@Cascade(CascadeType.ALL)
	@Fetch(FetchMode.SELECT)
    @BatchSize(size = 50)
	public Set<SlrAppointmentBookings> getSlrAppointmentBookingses() {
		return this.slrAppointmentBookingses;
	}

	public void setSlrAppointmentBookingses(
			Set<SlrAppointmentBookings> slrAppointmentBookingses) {
		this.slrAppointmentBookingses = slrAppointmentBookingses;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slrSeller")
	@Cascade(CascadeType.ALL)
	@Fetch(FetchMode.SELECT)
    @BatchSize(size = 50)
	public Set<SlrAmenities> getSlrAmenitieses() {
		return this.slrAmenitieses;
	}

	public void setSlrAmenitieses(Set<SlrAmenities> slrAmenitieses) {
		this.slrAmenitieses = slrAmenitieses;
	}


	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slrSeller")
	@Cascade(CascadeType.ALL)
	@Fetch(FetchMode.SELECT)
    @BatchSize(size = 50)
	public Set<SlrProduct> getSlrProducts() {
		return this.slrProducts;
	}

	public void setSlrProducts(Set<SlrProduct> slrProducts) {
		this.slrProducts = slrProducts;
	}
	

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slrSeller")
	@Cascade(CascadeType.ALL)
	@Fetch(FetchMode.SELECT)
    @BatchSize(size = 50)
	public Set<SlrDeal> getPrdDeals() {
		return prdDeals;
	}

	public void setPrdDeals(Set<SlrDeal> prdDeals) {
		this.prdDeals = prdDeals;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address")
	@Cascade(CascadeType.ALL)
	@Fetch(FetchMode.SELECT)
	public SlrAddress getSlrAddress() {
		return this.slrAddress;
	}

	public void setSlrAddress(SlrAddress slrAddress) {
		this.slrAddress = slrAddress;
	}
}
